
# This file was auto-generated by the NeoRadium's DeemMimoData class. Please do not edit manually.
from neoradium import DeepMimoData
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use("MacOSX")

DeepMimoData.setScenariosPath("/data/RayTracing/DeepMIMO/Scenarios/V4/")
deepMimoData = DeepMimoData("asu_campus_3p5", "BS", "rx_grid")
fig, ax = deepMimoData.drawMap("LOS-NLOS", figSize=6)

points = []
def onClick(event):
    x, y = event.xdata, event.ydata
    if x is not None and y is not None:
        if event.button == 1:
            if len(points)==0:  ax.plot(x, y, 'bo')
            else:               ax.plot([points[-1][0],x],[points[-1][1],y],'blue')
            points.append((x, y))
        elif event.button == 3:
            if len(points)==0:  return
            ax.plot([points[-2][0],points[-1][0]],[points[-2][1],points[-1][1]],'grey')
            points.pop()
        plt.draw()

plt.title("Map of LOS/NLOS paths\nClick on the map to add trajectory points")
cid = fig.canvas.mpl_connect('button_press_event', onClick)
plt.show()
print("Clicked points:", points)
